- name: Dart
  logo: dart
  url: https://dart.dev/
  color: 52C0F2
  projects:
    - https://github.com/fluttercommunity/import_sorter
    - https://github.com/Matt-Gleich/local_google_fonts
- name: Flutter
  logo: flutter
  url: https://flutter.dev/
  color: 52C0F2
  projects:
    - https://github.com/Matt-Gleich/Personal-Site
    - url: https://github.com/Matt-Gleich/Hack-Club-GP
      wip: true
    - url: https://github.com/Matt-Gleich/auralite-mobile
      wip: true
- name: Golang
  logo: go
  url: https://golang.org/
  color: 7FD6EA
  projects:
    - https://github.com/Matt-Gleich/gh_fsync
    - https://github.com/Matt-Gleich/nuke
    - https://github.com/Matt-Gleich/logoru
    - https://github.com/Matt-Gleich/statuser
    - https://github.com/Matt-Gleich/desktop
    - https://github.com/Matt-Gleich/new_release
    - url: https://github.com/Matt-Gleich/SimCmd
      wip: true
    - url: https://github.com/Matt-Gleich/texsch
      wip: true
    - url: https://github.com/Matt-Gleich/texsep
      wip: true
    - url: https://github.com/Matt-Gleich/eagleye
      wip: true
- name: Python
  logo: python
  url: https://www.python.org/
  color: 3C78A9
  projects:
    - https://github.com/Matt-Gleich/profile_stack
    - https://github.com/Matt-Gleich/Contribution-Hat
    - https://github.com/Matt-Gleich/RPi-Status
    - https://github.com/Matt-Gleich/Doc-Dockerfiles
    - https://github.com/Matt-Gleich/Quantum-Flip
    - https://github.com/Matt-Gleich/Photo-Sort
    - https://github.com/Team-501-The-PowerKnights/Vision2020
    - https://github.com/Team-501-The-PowerKnights/Powerknights-Slack-Bot
- name: React
  logo: react
  url: https://reactjs.org/
  color: 61DAFB
  projects:
    - https://github.com/Matt-Gleich/dynamic-season
    - https://github.com/Matt-Gleich/components
    - https://github.com/Matt-Gleich/jsx
- name: JavaScript
  logo: javascript
  url: https://github.com/Matt-Gleich?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  projects:
    - https://github.com/Matt-Gleich/components
    - https://github.com/Matt-Gleich/React-Translator
    - https://github.com/Matt-Gleich/Extreme-Fib-Calc
- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org
  color: 007ACC
  projects:
    - url: https://github.com/Matt-Gleich/emoji-clock
      wip: true
- name: Kubernetes
  logo: kubernetes
  url: https://kubernetes.io/
  color: 3D6DE6
  projects:
    - https://github.com/Matt-Gleich/kie
    - url: https://github.com/Matt-Gleich/fanboat
      wip: true
- name: Docker
  logo: docker
  url: https://www.docker.com/
  color: 4FA1EF
  projects:
    - https://github.com/Matt-Gleich/Dockerfiles
    - https://github.com/Matt-Gleich/profile_stack
    - https://github.com/Matt-Gleich/Control-Sense-Hat
